name: "Build Callback Action"
description: "Builds go-flare binaries for SLSA provenance"

inputs:
  slsa-workflow-inputs:
    description: "All inputs as JSON"
    required: true
  slsa-layout-file:
    description: "Location to store layout content"
    required: true
  registry:
    description: "Container registry"
    required: true
    default: ghcr.io
  image_name:
    description: "Image name (e.g. owner/repo/bitcoind)"
    required: true
  github_token:
    description: "GitHub token for registry auth"
    required: true

  # Unused secrets - framework requires these to be declared
  slsa-workflow-secret1: {}
  slsa-workflow-secret2: {}
  slsa-workflow-secret3: {}
  slsa-workflow-secret4: {}
  slsa-workflow-secret5: {}
  slsa-workflow-secret6: {}
  slsa-workflow-secret7: {}
  slsa-workflow-secret8: {}
  slsa-workflow-secret9: {}
  slsa-workflow-secret10: {}
  slsa-workflow-secret11: {}
  slsa-workflow-secret12: {}
  slsa-workflow-secret13: {}
  slsa-workflow-secret14: {}
  slsa-workflow-secret15: {}

outputs:
  attestations:
    description: "Attestation metadata for built artifacts"
    value: ${{ steps.generate-attestations.outputs.attestations }}
  image:
    description: "Published image tags"
    value: ${{ steps.meta.outputs.tags }}
  digest:
    description: "Image digest"
    value: ${{ steps.build-and-push.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

    - name: Get image tag (strip leading v only for tag)
      id: get_image_tag
      shell: bash
      run: |
        RAW_VERSION=$(grep "^ARG VERSION=" images/bitcoind/Dockerfile \
          | cut -d'=' -f2 \
          | tr -d '"' \
          | tr -d "'" \
          | tr -d '[:space:]')

        VERSION_FOR_GIT=$RAW_VERSION
        VERSION_FOR_TAG=${RAW_VERSION#v}

        echo "VERSION_FOR_GIT=${VERSION_FOR_GIT}" >> $GITHUB_ENV
        echo "VERSION_FOR_TAG=${VERSION_FOR_TAG}" >> $GITHUB_ENV

        echo "image_tag=${VERSION_FOR_TAG}" >> $GITHUB_OUTPUT

    - name: Install cosign
      if: ${{ github.event_name != 'pull_request' }}
      uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad
      with:
        cosign-release: "v2.5.3"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

    - name: Log into registry
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: |
          type=raw,value=${{ env.VERSION_FOR_TAG }}
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
        flavor: |
          latest=false

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
      with:
        context: images/bitcoind
        push: ${{ github.event_name != 'pull_request' }}
        build-args: |
          VERSION=${{ env.VERSION_FOR_GIT }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Sign the published Docker image
      if: ${{ github.event_name != 'pull_request' }}
      shell: bash
      env:
        TAGS: ${{ steps.meta.outputs.tags }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
      run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

    - name: Verify ghcr image signatures
      if: ${{ github.event_name != 'pull_request' }}
      shell: bash
      env:
        COSIGN_EXPERIMENTAL: 1
        TAGS: ${{ steps.meta.outputs.tags }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
      run: |
        echo "${TAGS}" | xargs -I {} cosign verify \
        --certificate-identity=https://github.com/${{ github.repository }}/.github/workflows/release-bitcoind.yml@${{ github.ref }} \
        --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
        "{}@${DIGEST}"

    - name: Generate SLSA layout file
      id: generate-attestations
      shell: bash
      run: |
        cat <<EOF > "${{ inputs.slsa-layout-file }}"
        {
          "artifacts": [
            {
              "name": "${{ steps.meta.outputs.tags }}",
              "digest": "${{ steps.build-and-push.outputs.digest }}"
            }
          ]
        }
        EOF

        echo "attestations=$(jq -c . "${{ inputs.slsa-layout-file }}")" >> $GITHUB_OUTPUT
