name: "Build Callback Action"
description: "Builds bitcoind image for SLSA provenance"

inputs:
  slsa-workflow-inputs:
    description: "All inputs as JSON"
    required: true
  slsa-layout-file:
    description: "Location to store layout content"
    required: true

  # Required dummy secrets for SLSA BYOB
  slsa-workflow-secret1:
    description: "hell"
    required: true

outputs:
  attestations:
    description: "Attestation metadata for built artifacts"
    value: ${{ steps.generate-attestations.outputs.attestations }}
  image:
    description: "Published image tags"
    value: ${{ steps.meta.outputs.tags }}
  digest:
    description: "Image digest"
    value: ${{ steps.build-and-push.outputs.digest }}

runs:
  using: "composite"
  steps:
    ###########################################################################
    # 1. Parse SLSA workflow inputs (THIS WAS THE MISSING PART)
    ###########################################################################
    - name: Parse SLSA workflow inputs
      id: parse
      shell: bash
      run: |
        echo "REGISTRY=$(echo '${{ inputs.slsa-workflow-inputs }}' | jq -r '.registry')" >> $GITHUB_ENV
        echo "IMAGE_NAME=$(echo '${{ inputs.slsa-workflow-inputs }}' | jq -r '.image_name')" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=$(echo '${{ inputs.slsa-workflow-secret1 }}')" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=$(echo '${{ inputs.slsa-workflow-secret1 }}')"

    ###########################################################################
    # 2. Build + Sign + Verify + Emit SLSA Layout
    ###########################################################################

    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

    - name: Get image tag (strip leading v only for tag)
      id: get_image_tag
      shell: bash
      run: |
        RAW_VERSION=$(grep "^ARG VERSION=" images/bitcoind/Dockerfile \
          | cut -d'=' -f2 \
          | tr -d '"' \
          | tr -d "'" \
          | tr -d '[:space:]')

        VERSION_FOR_GIT=$RAW_VERSION
        VERSION_FOR_TAG=${RAW_VERSION#v}

        echo "VERSION_FOR_GIT=${VERSION_FOR_GIT}" >> $GITHUB_ENV
        echo "VERSION_FOR_TAG=${VERSION_FOR_TAG}" >> $GITHUB_ENV

        echo "image_tag=${VERSION_FOR_TAG}" >> $GITHUB_OUTPUT

    - name: Install cosign
      if: ${{ github.event_name != 'pull_request' }}
      uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad
      with:
        cosign-release: "v2.5.3"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

    - name: Log into registry
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ env.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ env.VERSION_FOR_TAG }}
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
        flavor: |
          latest=false

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
      with:
        context: images/bitcoind
        push: ${{ github.event_name != 'pull_request' }}
        build-args: |
          VERSION=${{ env.VERSION_FOR_GIT }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output bundle
      id: out
      shell: bash
      env:
        TAGS: ${{ steps.meta.outputs.tags }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
        ATTEST: ${{ steps.generate-layout.outputs.attestations }}

      run: |
        FIRST_TAG=$(printf '%s\n' "$TAGS" | head -n1)
        echo "image=$FIRST_TAG" >> $GITHUB_OUTPUT
        echo "digest=$DIGEST" >> $GITHUB_OUTPUT
        echo "attestations=$ATTEST" >> $GITHUB_OUTPUT
    # - name: Sign the published Docker image if: ${{ github.event_name != 'pull_request' }}
    #   shell: bash
    #   env:
    #     TAGS: ${{ steps.meta.outputs.tags }}
    #     DIGEST: ${{ steps.build-and-push.outputs.digest }}
    #   run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
    #
    # - name: Verify ghcr image signatures
    #   if: ${{ github.event_name != 'pull_request' }}
    #   shell: bash
    #   env:
    #     COSIGN_EXPERIMENTAL: 1
    #     TAGS: ${{ steps.meta.outputs.tags }}
    #     DIGEST: ${{ steps.build-and-push.outputs.digest }}
    #   run: |
    #     echo "${TAGS}" | xargs -I {} cosign verify \
    #     --certificate-identity=https://github.com/${{ github.repository }}/.github/workflows/release-bitcoind.yml@${{ github.ref }} \
    #     --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
    #     "{}@${DIGEST}"
    - name: Generate layout file
      id: generate-layout
      env:
        SLSA_OUTPUTS_ARTIFACTS_FILE: ${{ inputs.slsa-layout-file }}
        BUILD_DIR: ./../__TOOL_CHECKOUT_DIR__/avalanchego/build
        BINARY_NAME: ${{ fromJSON(inputs.slsa-workflow-inputs).build_artifact_name }}
      shell: bash
      run: |
        set -euo pipefail

        mkdir -p "$(dirname "$SLSA_OUTPUTS_ARTIFACTS_FILE")"

        subjects=""
        for binary in "$BUILD_DIR/avalanchego" "$BUILD_DIR/plugins/evm"; do
          if [ -f "$binary" ]; then
            hash=$(sha256sum "$binary" | awk '{print $1}')
            subject_name=$(basename "$binary")

            [ -n "$subjects" ] && subjects+=","

            printf -v subject '{"name": "%s", "digest": {"sha256": "%s"}}' "$subject_name" "$hash"
            subjects+="$subject"
          fi
        done

        cat <<EOF > "$SLSA_OUTPUTS_ARTIFACTS_FILE"
        {
          "version": 1,
          "attestations": [{
            "name": "$BINARY_NAME-binaries",
            "subjects": [${subjects}]
          }]
        }
        EOF

        cat "$SLSA_OUTPUTS_ARTIFACTS_FILE"
